Add `diffutils` to test libraries
`diffutils` is a depenency of Google truth without it failing tests crash with `java.lang.NoClassDefFoundError: difflib/DiffUtils` instead of reporting the textual difference.

Fixes: https://github.com/bazelbuild/intellij/issues/2068
PiperOrigin-RevId: 456546902

GitOrigin-RevId: d196d1224b3fb376ed66b57fa372d504738f8339