fix `UltimatePluginModelTest.check` -
com.intellij.ide.plugins.PluginValidationError: No need to specify dependency on com.intellij.modules.platform (
  entry=PluginDependency(pluginId=com.intellij.modules.platform),
  referencingDescriptorFile=plugins/bazel/plugin-bazel/src/main/jps-resources/META-INF/plugin.xml
)

GitOrigin-RevId: 1e6cfb8a1a40017c01225a660da2fdfc404bdeda