Add compat layer for changes to AndroidDevice in 2021.2.
AndroidDevice has changed it's final paramater from Set<String> to Set<Abi>. Since the both method have the same type erasure, no method declaration in out FakeDevice can override both the before and after versions. For example, just removing the generic parameter gives this compiler error:

third_party/intellij/bazel/plugin/aswb/tests/integrationtests/com/google/idea/blaze/android/functional/MobileInstallBuildStepIntegrationTest.java:508: error: name clash:
  canRun(AndroidVersion,IAndroidTarget,AndroidFacet,Function<AndroidFacet,EnumSet<HardwareFeature>>,Set) in FakeDevice and
  canRun(AndroidVersion,IAndroidTarget,AndroidFacet,Function<AndroidFacet,EnumSet<HardwareFeature>>,Set<Abi>) in AndroidDevicei
have the same erasure, yet neither overrides the other

Introducing a base class to take care of the difference is on the only way I can see of resolving this.

PiperOrigin-RevId: 421574961