skyfocus: implement verification sets.
Verification sets are a key correctness feature of Skyfocus. It handles incremental builds of files that are __not__ in the working set. We can either:

1) Error out and ask the user to expand their working set.
2) Silently expand the working set for the user.

Both options require reanalysis to reconstruct the Skyframe graph. This CL implements the first option.

__Implementation detail__

Currently, verifications sets are implemented as a visitation on the downward transitive closure while performing the core Skyfocus algorithm (which propagates upwards). Skyfocus originally keeps the direct deps of the rdep TC of the working set; now it also keeps all reachable `FileStateKey`/`RootedPath`.

The verification set and working set are mutually exclusive.

The primary reason for keeping the verification set in-memory is to simply hook into the dirtiness checker infra, which relies on `FileSystemValueChecker#getDirtyKeys` [1] being called on the existent values of the backing graph.

The error handling is inserted into the `handleChangedFiles` step, where the changed `SkyKey`s are intersected against the verification set. If the result is non-empty, we end the build and print out the list of changed files/directories that should be added to the working set.

This CL increases the post-Skyfocus retained heap slightly, based on the benchmark below.

[1]: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java;l=3442;drc=7c1037dedf75444d323682000a86cc201aa64547

Example:

```
WARNING: Skyfocus: Changes not in the active working set will cause a build error. Run 'blaze info working_set' to print the set.
ERROR: Skyfocus detected changes outside of the working set. These files/directories must be added to the working set.
a/b.txt
```
(cherry picked from commit bfd4fdd894807307c4884ac7a0a2f2dfcffd7d06)